# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create Pods IP address block
      nsxt_ip_blocks:
        hostname: "{{manager_cluster_vip}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "pods-ip-block"
        state: "{{state}}"
        cidr: "172.26.0.0/24"

    - name: Create Nodes IP address block
      nsxt_ip_blocks:
        hostname: "{{manager_cluster_vip}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "nodes-ip-block"
        state: "{{state}}"
        cidr: "172.25.0.0/24"