# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create logical switch
      nsxt_logical_switches:
        hostname: "{{manager_cluster_vip}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "uplini1"
        replication_mode: SOURCE
        admin_state: UP
        transport_zone_name: "tz_uplink"
        vlan: 0
        state: "{{state}}"
      #with_items:
      #  - "{{logical_switches}}"
