# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
  - name: Generate private key
    openssl_privatekey:
      path: /home/vmware/certs/test.pem
      size: 2048
      state: present
  - name: Generate CSR
    openssl_csr:
      common_name: 192.168.110.42
      country_name: US
      email_address: dahr@vmware.com
      organization_name: NSX
      state_or_province_name: Texas
      locality_name: TX
      subject_alt_name: 'DNS:192.168.110.10'
      path: /home/vmware/certs/test.csr
      privatekey_path: /home/vmware/certs/test.pem
      state: present
  - name: Generate cert
    openssl_certificate:
      path: /home/vmware/certs/test.crt
      privatekey_path: /home/vmware/certs/test.pem
      csr_path: /home/vmware/certs/test.csr
      provider: selfsigned
      state: present